import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <div className="bg">
                    <img src="/img/bg.jpeg" alt="메인 배경 이미지" />
                </div>
                {children}
            </body>
        </html>
    );
}
